//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
fun main() {
    desafio1()
    ejercicio2()
    ejercicio3()
    ejercicio4()
    ejercicio5()
    ejercicio6()
    ejercicio7()
    ejercicio8()
    ejercicio9()
    ejercicio10()
    ejercicio11()
    ejercicio12()
    ejercicio13()
    ejercicio14()
    ejercicio15()
    ejercicio16()
    ejercicio17()
    ejercicio18()
    ejercicio19()
    ejercicio20()
    ejercicio21()
    ejercicio22()
    ejercicio23()
    ejercicio24()
    ejercicio25()
    ejercicio26()
    ejercicio27()
}
